package server;

public enum PayloadType {

	CONNECT, DISCONNECT, MESSAGE, CLEAR_PLAYERS, SYNC_DIRECTION, SYNC_POSITION, SHOOT, TEAM, ADD_TEAMMATE,
	REMOVE_TEAMMATE, PROJECTILE, START_GAME, SET_COUNTDOWN, END_GAME;
}
